version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout
            - run: |
                docker info
                if [[ -e ~/docker/image.tar ]]; then docker load --input ~/docker/image.tar; fi
                docker build --rm=false -t jonathanschmalhofer/udacitydeeplearning:latest .
                mkdir -p ~/docker; docker save jonathanschmalhofer/udacitydeeplearning:latest > ~/docker/image.tar
            - run: |
                docker run -d jonathanschmalhofer/udacitydeeplearning:latest /bin/bash -c "mkdir -p ~/my_workspace/src; cd ~/my_workspace/src; git clone https://github.com/JonathanSchmalhofer/octomap_catkin_gtest.git; cd ~/my_workspace" > ./dockerrun.log 2>&1
                cat ./dockerrun.log
            - run: |
                docker run -d jonathanschmalhofer/udacitydeeplearning:latest /bin/bash -c "source ~/udacity/miniconda/bin/activate; conda activate carnd-term1-cpu; conda list; echo 'import cv2' > test_environment.py; python test_environment.py" > ./dockerrun.log 2>&1
                cat ./dockerrun.log
            - run: |
                mkdir /tmp/artifacts
                ulimit -c unlimited
                docker save jonathanschmalhofer/udacitydeeplearning:latest > /tmp/artifacts/deeplearning.docker.bin
            - run: |
                docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                docker push jonathanschmalhofer/udacitydeeplearning:latest
            - store_artifacts:
                path: /tmp/artifacts